# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
trigger: # trigger only affects CI builds
    branches:
        include:
            - main

pr: # pr does not trigger CI builds
    branches:
        include:
            - '*' # must quote since "*" is a YAML reserved character; we want a string

variables:
    windowsImage: 'windows-2019'
    macImage: 'macOS-10.15'
    linuxImage: 'ubuntu-18.04'
    skipComponentGovernanceDetection: 'false'

jobs:
    - job: 'unit_tests_and_lints'

      pool:
          vmImage: $(linuxImage)

      steps:
          - template: pipeline/suppress-component-governance.yaml

          - template: pipeline/install-node-prerequisites.yaml

          - script: yarn lint:check:all
            displayName: check lint errors
            timeoutInMinutes: 5

          - script: yarn format:check
            displayName: check formatting errors
            timeoutInMinutes: 5

          - script: yarn copyright:check
            displayName: check copyrightheaders
            timeoutInMinutes: 1

          - script: yarn scss:build
            displayName: generate typings for scss files
            timeoutInMinutes: 3

          - script: yarn null:check
            displayName: check for strictNullChecks violations
            timeoutInMinutes: 5

          - script: yarn test --ci
            displayName: run unit tests
            timeoutInMinutes: 25

          - task: PublishTestResults@2
            inputs:
                testResultsFiles: $(System.DefaultWorkingDirectory)/test-results/unit/junit.xml
                testRunTitle: $(Agent.JobName)
            condition: always()
            displayName: publish test results
            timeoutInMinutes: 3

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: $(System.DefaultWorkingDirectory)/test-results/unit/coverage/cobertura-coverage.xml
                failIfCoverageEmpty: true
                # We care most about the summary information; adding the detailed files doesn't give enough extra information
                # to be worth the 1min it adds to the build.
                # Consider re-enabling this once https://github.com/Microsoft/azure-pipelines-tasks/issues/4945 is resolved.
                # reportDirectory: $(System.DefaultWorkingDirectory)/test-results/unit/coverage/lcov-report
            displayName: publish code coverage
            timeoutInMinutes: 5

          - script: yarn publish-code-coverage -t $(CODECOV_TOKEN)
            displayName: Publish code coverage to codecov
            timeoutInMinutes: 3
